
version: "3.7"

services:
  app:
    build: .
    networks:
      - web
    labels:
      - "traefik.http.routers.website-secure.rule=Host(`jupotter.eu`,`www.jupotter.eu`)"
      - "traefik.http.routers.website-secure.entrypoints=https"
      - "traefik.http.routers.website-secure.tls.certresolver=default"
      - "traefik.http.services.app-website.loadbalancer.server.port=80"
      - "traefik.enable=true"
    restart: always

networks:
  web:
    external: true
